INSERT INTO CRITERE VALUES ('robe','couleur du vin');
INSERT INTO CRITERE VALUES ('nez','odeur du vin');
INSERT INTO CRITERE VALUES ('gout','');
INSERT INTO CRITERE VALUES ('limpidité','transparence du vin');
INSERT INTO CRITERE VALUES ('intensité','force du vin');
INSERT INTO CRITERE VALUES ('consistance','niveau de liquidité du vin');
INSERT INTO CRITERE VALUES ('critere1','');
INSERT INTO CRITERE VALUES ('critere2','');
INSERT INTO CRITERE VALUES ('critere3','');
INSERT INTO CRITERE VALUES ('critere4','');